version: 2

models:
  - name: stg_users
    description: Contains user's information 

  - name: stg_addresses
    description: Contains additional address details

  - name: stg_events
    description: Contains customer level events

  - name: stg_order_items
    description:  Contains order and product ids

  - name: stg_orders
    description:  Contains order informations

  - name: stg_products
    description: Contains additional product information

  - name: stg_promos
    description: Contains information about any possible discounts

