version: 2

models:
  - name: stg_postgre_users
    description: Contains user's information 
    columns:
      - name: user_id
        tests: 
        - not_null

  - name: stg_postgre_addresses
    description: Contains additional address details

  - name: stg_postgre_events
    description: Contains customer level events

  - name: stg_postgre_order_items
    description:  Contains order and product ids

  - name: stg_postgre_orders
    description:  Contains order informations

  - name: stg_postgre_products
    description: Contains additional product information

  - name: stg_postgre_promos
    description: Contains information about any possible discounts

